/**
 * Minimal single-page PDF writer (Helvetica, text only) for the portal's
 * downloadable documents. No dependency needed for plain text documents.
 */

const PAGE_WIDTH = 612; // US Letter, in points
const PAGE_HEIGHT = 792;
const MARGIN = 72;
const MAX_CHARS_PER_LINE = 88;

// The standard PDF fonts only cover Latin-1, so map common typographic characters.
const toPdfText = (text) =>
  text
    .replace(/₱/g, 'PHP ')
    .replace(/[–—]/g, '-')
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/…/g, '...')
    .replace(/[^\x20-\x7E]/g, '')
    .replace(/[\\()]/g, (char) => `\\${char}`);

function wrap(line) {
  if (line.length <= MAX_CHARS_PER_LINE) return [line];
  const words = line.split(' ');
  const lines = [];
  let current = '';
  for (const word of words) {
    if (`${current} ${word}`.trim().length > MAX_CHARS_PER_LINE) {
      lines.push(current);
      current = word;
    } else {
      current = `${current} ${word}`.trim();
    }
  }
  if (current) lines.push(current);
  return lines;
}

/**
 * @param {{ heading?: string, title: string, lines: string[], footer?: string }} doc
 * @returns {Blob}
 */
export function createTextPdf({ heading, title, lines, footer }) {
  const ops = ['BT'];
  let y = PAGE_HEIGHT - MARGIN;

  if (heading) {
    ops.push(`/F1 10 Tf 1 0 0 1 ${MARGIN} ${y} Tm (${toPdfText(heading)}) Tj`);
    y -= 28;
  }
  ops.push(`/F2 16 Tf 1 0 0 1 ${MARGIN} ${y} Tm (${toPdfText(title)}) Tj`);
  y -= 32;

  ops.push('/F1 11 Tf');
  for (const line of lines.flatMap(wrap)) {
    ops.push(`1 0 0 1 ${MARGIN} ${y} Tm (${toPdfText(line)}) Tj`);
    y -= 17;
  }

  if (footer) {
    ops.push(`/F1 8 Tf 1 0 0 1 ${MARGIN} ${MARGIN / 2} Tm (${toPdfText(footer)}) Tj`);
  }
  ops.push('ET');

  const stream = ops.join('\n');
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>`,
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>',
  ];

  // Everything is ASCII, so string length equals byte length for the xref offsets.
  let pdf = '%PDF-1.4\n';
  const offsets = objects.map((body, index) => {
    const offset = pdf.length;
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
    return offset;
  });

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  pdf += offsets.map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`).join('');
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return new Blob([pdf], { type: 'application/pdf' });
}

export function downloadBlob(blob, fileName) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  link.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export const SAMPLE_FOOTER = 'SAMPLE DOCUMENT generated by the student portal demo - not valid as an official record.';
